### ISSUE TITLE
Unprotecting

### ISSUE THREAD

**Issue by thechangingchange** [stefanzweifel/dirby#2]
Hi there, great theme. But is there any quick way to unprotect the pages? Right now, one needs to login to see all the pages. 

> All dirby-pages are protected and only visible to logged in users (No .htaccess Auth required)

**Comment by thechangingchange** [comment]
Too bad, Dirby project seems to be dead :(

**Comment by stefanzweifel** [comment]
Hey @thechangingchange 

Sorry that I didn't respond to your issue (I somehow didn't get a notification 18 days ago :().

You only have to remove this [this](https://github.com/stefanzweifel/dirby/blob/master/site/templates/dirby.php#L1) from the template.

----

And this is "just" a theme, not a project. The theme worked for me, but I moved on ...

**Comment by thechangingchange** [comment]
Thanks so much. One last question.. I removed it but I do not see full navigation bar. (I can only open the pages if I have the direct links). Is there anything I can do? Thanks again,

**Comment by stefanzweifel** [comment]
You should edit this file [here](https://github.com/stefanzweifel/dirby/blob/master/site/snippets/dirby/layout/navigation.php#L29-L49). Just remove the if / else clause and you should be ready to go.

----
(Seems Github has issues with their emails. Still didn't get a notification email ...)
